#! /bin/bash

updateFixes () {
    cd /usr/LuaSpace
    sudo rm -rf LuaSpaceFixes
    git clone https://gitlab.com/svaltek/DevTools/alpine-luadev-fixes.git
    mv /usr/LuaSpace/alpine-luadev-fixes /usr/LuaSpace/LuaSpaceFixes
    chmod +x -R /usr/LuaSpace/LuaSpaceFixes/*
}

clear
echo ''
echo ' LuaSpace Updating'

# Update LuaDev FixScripts
updateFixes

echo ''
echo ' All Done...'
cd ~/