#! /bin/bash

updateFixes () {
    cd /usr/LuaSpace
    git clone https://gitlab.com/svaltek/DevTools/alpine-luadev-fixes.git
    mv alpine-luadev-fixes LuaSpaceFixes
    chmod +x -R /usr/LuaSpace/LuaSpaceFixes/*
}

clear
echo ''
echo ' LuaSpace Updating'

# Update LuaDev FixScripts
updateFixes

echo ''
echo ' All Done...'
cd ~/